[app_servers]
app1 ansible_host=54.209.209.114 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/school_mgmt_key
app2 ansible_host=13.219.225.61 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/school_mgmt_key

[vault_server]
vault ansible_host=10.0.3.114 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/school_mgmt_key

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
