[app_servers]
app1 ansible_host=REPLACE_WITH_APP1_IP ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/school_mgmt_key
app2 ansible_host=REPLACE_WITH_APP2_IP ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/school_mgmt_key

[vault_server]
vault ansible_host=REPLACE_WITH_VAULT_IP ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/school_mgmt_key

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
